### ISSUE TITLE
Not sure if bug, or just using it wrong

### ISSUE THREAD

**Issue by ZenithAstralis** [obp3ter/scarpet-os-utils#8]
**Describe the bug**
Can not use os_exec() to run os commands (notepad)

**To Reproduce**
1. open chat in minecraft
2. enter and execute `/script run os_exec(notepad)`
3. error received:
```
Cannot run program "0": CreateProcess error=2, The system cannot find the file specified in system chat at pos 1
HERE>> os_exec(notepad)
```

**Expected behavior**
open notepad maybe? I'm just trying to figure out how to run things with system commands, and am new the Scarpet

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version: scarpet-os-utils-1.16.5-1.4.24
 - Carpet: fabric-carpet-1.16.5-1.4.28+v210224
 - Fabric: fabric-api-0.32.0+1.16
 - Via jumploader-2.1.3
 - Via Forge 36.0.46

**Additional context**
I can get `/script run get_os()` to return **`Windows 10`** just fine

**Comment by obp3ter** [comment]
You are missing some quotes -> /script run os_exec('notepad')
Even though this works, I really didn't have GUI apps in mind when I made this.
